[package]
name = "cuyat"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
cursive = "0.20"
itertools = "0.13.0"
nalgebra = { version = "0.33.0", features = ["rand"] }
regex = "1.10.5"
